branches:
  only:
    - master
    - dev

notifications:
  irc:
    channels:
      - "chat.freenode.net#solarus"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true


language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libluajit-5.1-dev
    - libphysfs-dev
    - libopenal-dev
    - libmodplug-dev
    - libvorbis-dev
    - libglm-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools

install:
# The Solarus library is also a dependency. A branch of the editor is
# supposed to compile with the same branch of Solarus.
  - git clone --branch=$TRAVIS_BRANCH https://github.com/christopho/solarus
  - cd solarus && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && sudo make install && cd ../..

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make

